main: global_includes.h learning_machine.cpp learning_machine.h lecturer_msc.cpp lecturer_msc.h lecturer_phd.cpp lecturer_phd.h main.cpp person.cpp person.h staff.cpp staff.h student.cpp student.h
	g++ -o main learning_machine.cpp lecturer_msc.cpp lecturer_phd.cpp main.cpp person.cpp staff.cpp student.cpp

run: main
	./main
